/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Order
 */
class Order extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.petId = this.constructor.getValue(obj.petId);
        this.quantity = this.constructor.getValue(obj.quantity);
        this.shipDate = this.constructor.getValue(obj.shipDate);
        this.status = this.constructor.getValue(obj.status);
        this.complete = this.constructor.getValue(obj.complete, false);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'petId', realName: 'petId' },
            { name: 'quantity', realName: 'quantity' },
            { name: 'shipDate', realName: 'shipDate', isDateTime: true, dateTimeValue: 'rfc3339' },
            { name: 'status', realName: 'status' },
            { name: 'complete', realName: 'complete' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Order;
