/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of Pet
 */
class Pet extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.category = this.constructor.getValue(obj.category);
        this.name = this.constructor.getValue(obj.name);
        this.photoUrls = this.constructor.getValue(obj.photoUrls);
        this.tags = this.constructor.getValue(obj.tags);
        this.status = this.constructor.getValue(obj.status);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'category', realName: 'category', type: 'Category' },
            { name: 'name', realName: 'name' },
            { name: 'photoUrls', realName: 'photoUrls', array: true },
            { name: 'tags', realName: 'tags', array: true, type: 'Tag' },
            { name: 'status', realName: 'status' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = Pet;
