/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const StatusEnum = {

    /**
     * TODO: Write general description for this element
     */
    PLACED: 'placed',

    /**
     * TODO: Write general description for this element
     */
    APPROVED: 'approved',

    /**
     * TODO: Write general description for this element
     */
    DELIVERED: 'delivered',

};

module.exports = StatusEnum;
