/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const BaseModel = require('./BaseModel');

/**
 * Creates an instance of User
 */
class User extends BaseModel {
    /**
     * @constructor
     * @param   {Object}  obj    The object passed to constructor
     */
    constructor(obj) {
        super(obj);
        if (obj === undefined || obj === null) return;
        this.id = this.constructor.getValue(obj.id);
        this.username = this.constructor.getValue(obj.username);
        this.firstName = this.constructor.getValue(obj.firstName);
        this.lastName = this.constructor.getValue(obj.lastName);
        this.email = this.constructor.getValue(obj.email);
        this.password = this.constructor.getValue(obj.password);
        this.phone = this.constructor.getValue(obj.phone);
        this.userStatus = this.constructor.getValue(obj.userStatus);
    }

    /**
     * Function containing information about the fields of this model
     * @return   {array}   Array of objects containing information about the fields
     */
    static mappingInfo() {
        return super.mappingInfo().concat([
            { name: 'id', realName: 'id' },
            { name: 'username', realName: 'username' },
            { name: 'firstName', realName: 'firstName' },
            { name: 'lastName', realName: 'lastName' },
            { name: 'email', realName: 'email' },
            { name: 'password', realName: 'password' },
            { name: 'phone', realName: 'phone' },
            { name: 'userStatus', realName: 'userStatus' },
        ]);
    }

    /**
     * Function containing information about discriminator values
     * mapped with their corresponding model class names
     *
     * @return   {object}  Object containing Key-Value pairs mapping discriminator
     *                     values with their corresponding model classes
     */
    static discriminatorMap() {
        return {};
    }
}

module.exports = User;
