/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const servers = require('./Servers');
const environments = require('./Environments');
const apiHelper = require('./APIHelper');

const environmentsMap = [];

environmentsMap[environments.PRODUCTION] = [];
environmentsMap[environments.ENVIRONMENT_2] = [];
environmentsMap[environments.ENVIRONMENT_3] = [];

environmentsMap[environments.PRODUCTION][servers.MDEFAULT] =
    'https://virtserver.swaggerhub.com/teretz/scratch/1.0.0';
environmentsMap[environments.ENVIRONMENT_2][servers.MDEFAULT] =
    'https://virtserver.swaggerhub.com/teretz/fromscrtach/1.0.0';
environmentsMap[environments.ENVIRONMENT_3][servers.MDEFAULT] = 'https://petstore.swagger.io/v2';

const Configuration = {
    apiKey: '',

    /**
     * Current API environment
     * @type {string}
     */
    currentEnvironment: environments.PRODUCTION,

    /**
     * Get base URI for a server in the current API environment
     * @param  {string|null} server Server name
     * @return {string}             Base URI for server
     */
    getBaseUri(server) {
        const url = environmentsMap[this.currentEnvironment][server || servers.MDEFAULT];
        const urlParams = {
        };
        return apiHelper.appendUrlWithTemplateParameters(url, urlParams);
    },
};

module.exports = Configuration;
