/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Environments = {

    /**
     * SwaggerHub API Auto Mocking
     */
    PRODUCTION: 'production',

    /**
     * SwaggerHub API Auto Mocking
     */
    ENVIRONMENT_2: 'environment2',

    /**
     * TODO: Write general description for this element
     */
    ENVIRONMENT_3: 'environment3',

};

module.exports = Environments;
