/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

'use strict';

const Order = require('../lib/Models/Order');
const Category = require('../lib/Models/Category');
const User = require('../lib/Models/User');
const Tag = require('../lib/Models/Tag');
const Indicator = require('../lib/Models/Indicator');
const Pet = require('../lib/Models/Pet');
const ApiResponse = require('../lib/Models/ApiResponse');
const Body = require('../lib/Models/Body');
const Body1 = require('../lib/Models/Body1');

const classMap = {
    Order,
    Category,
    User,
    Tag,
    Indicator,
    Pet,
    ApiResponse,
    Body,
    Body1,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
